# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: control.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcontrol.proto\x12\x07\x63ontrol\"(\n\rTurnOnRequest\x12\x17\n\x0fmic_name_target\x18\x01 \x01(\t\"\x10\n\x0eTurnOffRequest\"\x19\n\x06Status\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x0eWeatherRequest\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\"8\n\x0fWeatherResponse\x12\x14\n\x0cweather_info\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32x\n\x0e\x43ontrolService\x12\x31\n\x06TurnOn\x12\x16.control.TurnOnRequest\x1a\x0f.control.Status\x12\x33\n\x07TurnOff\x12\x17.control.TurnOffRequest\x1a\x0f.control.Status2^\n\x10\x43SharpApiService\x12J\n\x15GetWeatherInformation\x12\x17.control.WeatherRequest\x1a\x18.control.WeatherResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TURNONREQUEST']._serialized_start=26
  _globals['_TURNONREQUEST']._serialized_end=66
  _globals['_TURNOFFREQUEST']._serialized_start=68
  _globals['_TURNOFFREQUEST']._serialized_end=84
  _globals['_STATUS']._serialized_start=86
  _globals['_STATUS']._serialized_end=111
  _globals['_WEATHERREQUEST']._serialized_start=113
  _globals['_WEATHERREQUEST']._serialized_end=143
  _globals['_WEATHERRESPONSE']._serialized_start=145
  _globals['_WEATHERRESPONSE']._serialized_end=201
  _globals['_CONTROLSERVICE']._serialized_start=203
  _globals['_CONTROLSERVICE']._serialized_end=323
  _globals['_CSHARPAPISERVICE']._serialized_start=325
  _globals['_CSHARPAPISERVICE']._serialized_end=419
# @@protoc_insertion_point(module_scope)
