# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: assistant_bridge.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'assistant_bridge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61ssistant_bridge.proto\" \n\rGeminiRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\'\n\x13\x41\x63tivateFormRequest\x12\x10\n\x08\x61\x63tivate\x18\x01 \x01(\x08\"#\n\x0eGeminiResponse\x12\x11\n\tresponses\x18\x01 \x03(\t\"\x1b\n\x0b\x43ityRequest\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\"$\n\x0c\x43ityResponse\x12\x14\n\x0c\x66ullCityName\x18\x01 \x01(\t\"I\n\x0fWeatherResponse\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x13\n\x0btemperature\x18\x03 \x01(\x01\"*\n\x06Status\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xc5\x01\n\x0f\x41ssistantBridge\x12-\n\nGeminiQues\x12\x0e.GeminiRequest\x1a\x0f.GeminiResponse\x12&\n\x07GetCity\x12\x0c.CityRequest\x1a\r.CityResponse\x12,\n\nGetWeather\x12\x0c.CityRequest\x1a\x10.WeatherResponse\x12-\n\x0c\x41\x63tivateForm\x12\x14.ActivateFormRequest\x1a\x07.Statusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'assistant_bridge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GEMINIREQUEST']._serialized_start=26
  _globals['_GEMINIREQUEST']._serialized_end=58
  _globals['_ACTIVATEFORMREQUEST']._serialized_start=60
  _globals['_ACTIVATEFORMREQUEST']._serialized_end=99
  _globals['_GEMINIRESPONSE']._serialized_start=101
  _globals['_GEMINIRESPONSE']._serialized_end=136
  _globals['_CITYREQUEST']._serialized_start=138
  _globals['_CITYREQUEST']._serialized_end=165
  _globals['_CITYRESPONSE']._serialized_start=167
  _globals['_CITYRESPONSE']._serialized_end=203
  _globals['_WEATHERRESPONSE']._serialized_start=205
  _globals['_WEATHERRESPONSE']._serialized_end=278
  _globals['_STATUS']._serialized_start=280
  _globals['_STATUS']._serialized_end=322
  _globals['_ASSISTANTBRIDGE']._serialized_start=325
  _globals['_ASSISTANTBRIDGE']._serialized_end=522
# @@protoc_insertion_point(module_scope)
